# Generated by Django 4.2.7 on 2024-02-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeBack", "0002_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
